language: python

python:
 - "3.6"

install:
 - pip3 install urllib3

script:
 - python src/srconfig.py

after_script:
 - git config user.name "hayden"
 - git config user.email "yangxinhust@hotmail.com"
 - git remote rm origin
 - git remote add origin https://Hsiny:${GH_TOKEN}@github.com/Hsiny/Shadowrocket-Config.git
 - git add -A
 - git commit -m "Dayly Update by CI"
 - git push origin travis