language: python

install:
 - pip install requests

script:
 - python src/srconfig.py

after_script:
 - git config user.name "hayden"
 - git config user.email "yangxinhust@hotmail.com"
 - git add -A
 - git commit -m "Dayil Update"
 - git push